name: Build and deploy Python app to Azure Web App - incidents-and-claims

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare deployment folder
        run: |
          mkdir deploy
          cp backend/app/main.py deploy/
          cp backend/requirements.txt deploy/
          cp -r backend/app deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: incidents-and-claims
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0674D84D33534B478017F4629F8EBB62 }}
